# Generated by Django 4.2.9 on 2024-02-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_total_price_order_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
